name: Development Build (Galaxy A50)

on:
  workflow_dispatch:
  push:
    branches:
      - "wip-*"

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        type: [
            oneui-12-e,
            oneui-12-p,
            oneui-11-e,
            oneui-11-p,
            aosp-12-e,
            aosp-12-p,
            aosp-11-e,
            aosp-11-p,
          ]

    steps:
      - uses: actions/checkout@v4

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Manila"

      - name: Export build branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Update Debian/Ubuntu Repositories
        run: sudo apt-get update

      - name: Install Debian/Ubuntu dependencies
        run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

      - name: Parse build arguments
        run: |
          echo "VARIANT=$(echo ${{ matrix.type }} | cut -d '-' -f1)" >> $GITHUB_ENV
          echo "ANDROID=$(echo ${{ matrix.type }} | cut -d '-' -f2)" >> $GITHUB_ENV
          echo "SELINUX=$(echo ${{ matrix.type }} | cut -d '-' -f3)" >> $GITHUB_ENV

      - name: Build Mint kernel (No-Root)
        run: |
          set -eo pipefail
          ./build.sh --automated --device a50 --variant $VARIANT --android $ANDROID -$SELINUX

      - name: Upload kernel image artifact (No-Root)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}-NoRoot-Image
          path: out/boot.img

      - name: Build Mint kernel (KernelSU)
        run: |
          set -eo pipefail
          ./build.sh --automated --device a50 --variant $VARIANT --android $ANDROID -$SELINUX --kernelsu

      - name: Upload kernel image artifact (KernelSU)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}-KernelSU-Image
          path: out/boot.img

      - name: Prepare release package
        run: |
          mkdir -p ./release
          # Safely move files only if they exist to avoid mv errors
          find ./out -type f -iname "MintBeta-*.zip" -exec mv -f {} ./release/ \;
          cp .config "./release/kernel_config_a50_$VARIANT-$ANDROID-$SELINUX.txt"

      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}-Release
          path: release/

  release:
    name: Release files and configs
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all release artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release
          pattern: "*-Release"
          merge-multiple: true

      - name: Cleanup release directory
        run: |
          rm -f ./release/kernel_config_*.txt
          # Delete any leftover folders from the download process
          find ./release -mindepth 1 -type d -exec rm -rf {} +

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 12
          delete_tag_pattern: "xbeta"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: xbeta-${{ github.run_number }}_a50dx
          prerelease: true
          name: Galaxy A50 (beta-${{ github.run_number }})
          body_path: "./tools/make/release/a50-development.md"
          files: "./release/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
